export const SET_PEOPLE_LIST="SET_PEOPLE_LIST";
export const SET_PLANET_LIST="SET_PLANET_LIST";
export const SET_FILM_LIST="SET_FILM_LIST";
export const FETCH_LIST_REQUEST="FETCH_LIST_REQUEST";
export const FETCH_LIST_SUCCESS="FETCH_LIST_SUCCESS";