export const SET_PEOPLE_LIST = "SET_PEOPLE_LIST";
export const SET_PLANET_LIST = "SET_PLANET_LIST";
export const SET_FILM_LIST = "SET_FILM_LIST";
export const FETCH_LIST_REQUESTED = "FETCH_LIST_REQUESTED";
export const FETCH_PLANETLIST_REQUESTED = "FETCH_PLANETLIST_REQUESTED";
export const FETCH_PEOPLELIST_REQUESTED = "FETCH_PEOPLELIST_REQUESTED";
export const FETCH_FILMLIST_REQUESTED = "FETCH_FILMLIST_REQUESTED";
